services:
  frontend:
    build:
      context: ./my-leak-dashboard # Build context is your React app directory
      dockerfile: ../Dockerfile.frontend # Reference the frontend Dockerfile
    ports:
      - "3000:3000" # Map host port 3000 to container port 3000 (React dev server)
    depends_on:
      - backend # Frontend still depends on backend being ready for API calls
    environment:
      # Optional: To tell React app that it's running in container and API is at 'backend'
      # This is useful if you didn't change API_BASE_URL to '' in App.jsx
      # REACT_APP_API_BASE_URL: http://backend:8001
      # Note: For this setup, React app will connect to backend:8001 directly.
      # You must update API_BASE_URL in your React App.jsx to 'http://backend:8001'
      # or adjust the fetch calls to use relative paths if you set it to ''.
      # For simplicity in Docker Compose, 'http://backend:8001' is clearer.
      CHOKIDAR_USEPOLLING: "true" # Fixes hot reloading issues in Docker

  backend:
    build:
      context: ./backend # Build context is the root directory for FastAPI files
      dockerfile: ../Dockerfile.backend # Reference the backend Dockerfile
    ports:
      - "8001:8001" # Map host port 8001 to container port 8001 (FastAPI)
    # Expose the port for the backend within the Docker network (not directly exposed to host)
    # This allows the frontend to access it by service name 'backend'
    expose:
      - "8001"
